CXX=icpc
CXXFLAGS=-O3 -xHost -qopenmp ${LIKWID_INC}
LDFLAGS=-qopenmp ${LIKWID_LIB}
DEFINES=-DLIKWID_PERFMON
SOURCES=dtrmv.cpp
OBJECTS=$(SOURCES:.cpp=.o)
EXECUTABLE=dtrmv

all: $(SOURCES) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(CXX) $(LDFLAGS) $(OBJECTS) -o $@

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $< -o $@ $(DEFINES)

$(SOURCES): Makefile.dtrmv
	touch $@

clean:
	rm *.o *.optrpt $(EXECUTABLE)
