#ifndef CONSTANTS_H_
#define CONSTANTS_H_

#define NUMBER_OF_BASIS_FUNCTIONS (CONVERGENCE_ORDER*(CONVERGENCE_ORDER+1)/2)
#define NUMBER_OF_QUANTITIES 3

#define NUMBER_OF_DOFS (NUMBER_OF_BASIS_FUNCTIONS*NUMBER_OF_QUANTITIES)

#define GLOBAL_MATRIX_SIZE (NUMBER_OF_BASIS_FUNCTIONS*NUMBER_OF_BASIS_FUNCTIONS)

#define UP    0
#define DOWN  1
#define LEFT  2
#define RIGHT 3

#define ALIGNMENT 64

#endif // CONSTANTS_H_
